version: "3.9"
name: schedule_app_stg

services:
  backend:
    working_dir: /app
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    networks:
      - schedule_app_network
    image: schedule_app-backend-stg:latest
    container_name: schedule_app-backend-stg
    restart: always
    env_file: .env
    depends_on:
      - db

  nginx-stg:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: /api
    networks:
      - schedule_app_network
    image: schedule_app-nginx-stg:latest
    container_name: schedule_app-nginx-stg
    env_file:
      - .env
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    networks:
      - schedule_app_network
    image: postgres:15
    container_name: schedule_app-db-stg
    restart: always
    env_file: .env
    volumes:
      - postgres_data_stg:/var/lib/postgresql/data

volumes:
  postgres_data_stg:

networks:
  schedule_app_network:
    external: true
