version: "3.9"

services:
  ingress-nginx:
    image: nginx:alpine
    container_name: ingress-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/ingress.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - schedule_app_network

networks:
  schedule_app_network:
    external: true
