version: "3.9"

services:
  backend:
    working_dir: /app
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    image: schedule_app-backend:latest
    restart: always
    env_file: .env.prod
    depends_on:
      - db
    networks:
      - schedule_app_prod_net

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: /api
    image: schedule_app-frontend:latest
    env_file:
      - .env.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - schedule_app_prod_net

  ingress-nginx:
    image: nginx:alpine
    container_name: ingress-nginx-prod
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../infra/nginx/ingress.common.conf:/etc/nginx/ingress.common.conf:ro
      - ../../infra/nginx/ingress.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - schedule_app_prod_net

  db:
    image: postgres:15
    restart: always
    env_file: .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - schedule_app_prod_net

volumes:
  postgres_data:

networks:
  schedule_app_prod_net:
    driver: bridge
